title: project
pages:
  template: default
  build:
    - title: _modules
      uid: modules
      template: modules
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  imageurl:
    label: Image Url
    type:  url

  sortable:
    label: sortable
    type:  sortable

    sortable: true

    layout:  base
    variant: null

    limit: false

    parent: null
    prefix: null

    options:
      limit: false
